<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="24.247" timestamp="2021-02-25T18:41:32.123222" hostname="barrachina-SONDRA"><testcase classname="" name="tests.test_several_datasets" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/home/barrachina/Documents/cvnn/tests/test_several_datasets.py", line 10, in &lt;module&gt;
    from cvnn.montecarlo import run_gaussian_dataset_montecarlo
  File "/home/barrachina/Documents/cvnn/cvnn/montecarlo.py", line 29, in &lt;module&gt;
    logger = logging.getLogger(cvnn.__name__)
NameError: name 'cvnn' is not defined</error></testcase></testsuite></testsuites>